[package]
name = "todo-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
dotenv = "0.15.0"
envy = "0.4.2"
serde = { version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
